# Generated by Django 5.0 on 2024-01-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_mobailno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='mobailno',
            new_name='phoneno',
        ),
    ]
